### ISSUE TITLE
build_html: float object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by aaronnguyen** [aaronnguyen/db-flat-diff#1]
> renderer.js:124 exec error: 
> Error: Command failed: cd /Applications/FlatDiff.app/Contents/Resources/app/py && 
> ./flatten_diff 
> --electron_root "/Applications/FlatDiff.app/Contents/Resources/app" 
> --output diff.html 
> "/private/var/folders/......1.xml" 
> "/private/var/folders/......2.xml"
> [26773] Failed to execute script flatten_diff
> Traceback (most recent call last):
>   File "flatten_diff.py", line 57, in <module>
>   File "build_html.py", line 279, in full_html_process
>   File "build_html.py", line 156, in build_diff_html
>   File "build_html.py", line 27, in build_empty_string
> TypeError: 'float' object cannot be interpreted as an integer
> 
> exec @ renderer.js:124
> exithandler @ child_process.js:230
> emitTwo @ events.js:106
> emit @ events.js:191
> maybeClose @ internal/child_process.js:885
> (anonymous) @ internal/child_process.js:334
> emitOne @ events.js:96
> emit @ events.js:188
> _handle.close @ net.js:501

**Comment by aaronnguyen** [comment]
commit ae0be52ddba707d4fc22e345323c44c7f24893a1 resolves this bug
